# Numpy



`NumPy` is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [30]:
#Importing numpy package and aliasing it to shorten the name 

import numpy as np

# Why use NumPy?

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU

# Numpy arrays

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

 

Most NumPy arrays have some restrictions. For instance:

All elements of the array must be of the same type of data.

Once created, the total size of the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

For the remainder of this document, we will use the word “array” to refer to an instance of ndarray.

In [44]:
# Initialize numpy arrays.

#Method 1 : pass a python list

python_list = [1, 2, 3, 4, 5, 6]
a = np.array(python_list)

print(a)

print(type(a))


#help(a) => uncomment this to view the functions and properties of numpy class





[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Accessing the elements of a numpy array

Elements of an array can be accessed in various ways.we can access an element in the original list: using the integer index of the element within square brackets.As with built-in Python sequences, NumPy arrays are “0-indexed”: the first element of the array is accessed using index 0, not 1


In [60]:
#Example of accessing elements of an array

print(a)
print("The first element of the array is : " ,a[0])
print("The second element of the array is : ",a[1])
print("The third element of the array is : " ,a[2])
print("The fourth element of the array is : ",a[3])
print("The fifth element of the array is : " ,a[4])
print("The last element of the array is : "  ,a[5])




[1 2 3 4 5 6]
The first element of the array is :  1
The second element of the array is :  2
The third element of the array is :  3
The fourth element of the array is :  4
The fifth element of the array is :  5
The last element of the array is :  6



* Like the normal  list, the numpy array is mutable.
* Also Python slice notation can be used for indexing



In [67]:
#testing  mutability of a numpy array
print("Array before the change",a)
a[0] = 10

print ("Array after the change ", a)

Array before the change [1 2 3 4 5 6]
Array after the change  [10  2  3  4  5  6]


In [83]:
#Slicing the numpy array


# syntax of slicing  a[start:stop:steps] by default start=0 when not specified

print("the first 3 elements are ", a[:3])

print("the last 3 elements are ", a[-1:-4:-1])





the first 3 elements are  [10  2  3]
the last 3 elements are  [6 5 4]


One major difference is that **slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array**. The original array can be mutated using the view.**This is dangerous and care should be taken**

In [114]:
#Example of the  copying(Python list) vs views(numpy array)

lengths = [2,4,5,6,7,7,10]
truncated_lengths=lengths[:3]

print("Before  modification python list ",lengths)
print("Before modification python list",truncated_lengths)

# lets modify the first index of truncated length

truncated_lengths[0]=1000

print("After  modification python list",lengths)
print("After  modification python list",truncated_lengths)















Before  modification python list  [2, 4, 5, 6, 7, 7, 10]
Before modification python list [2, 4, 5]
After  modification python list [2, 4, 5, 6, 7, 7, 10]
After  modification python list [1000, 4, 5]


In [116]:
#For numpy array(view) =>  

numpy_lengths = np.array([2,4,5,6,7,7,10])
numpy_truncated_lengths=numpy_lengths[:3]

print("Before  modification numpy array ",numpy_lengths)
print("Before modification numpy array",numpy_truncated_lengths)

# lets modify the first index of truncated length

numpy_truncated_lengths[0]=1000


print("After  modification numpy array",numpy_truncated_lengths)
print("After  modification numpy array",numpy_lengths)

Before  modification numpy array  [ 2  4  5  6  7  7 10]
Before modification numpy array [2 4 5]
After  modification numpy array [1000    4    5]
After  modification numpy array [1000    4    5    6    7    7   10]


In [130]:
# To check if a numpy array is a view , return None if its a copy

print(numpy_truncated_lengths.base)

print(numpy_truncated_lengths.base is None)

[1000    4    5    6    7    7   10]
False


# 2D ARRAYS OF MATRICES

Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [136]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
type(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


numpy.ndarray

In [144]:
#properties of numpy arrays

print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 4)
12


# How to create other basic array

In [147]:
##Try this and see what happens

np.zeros(2)
np.ones(2)

# Create an empty array with 2 elements
np.empty(2) 

np.arange(4)

np.arange(2, 9, 2)

np.linspace(0, 10, num=5)

x = np.ones(2, dtype=np.int64)




# Adding, removing, and sorting elements

Sorting an array is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [151]:
#Example of sorting 

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [153]:
#concatenation

c = np.array([1, 2, 3, 4])
d = np.array([5, 6, 7, 8])

np.concatenate((c, d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [155]:
#Can you reshape an array?=> use reshape

arr.reshape(4,2)



array([[2, 1],
       [5, 3],
       [7, 4],
       [6, 8]])